name: duet

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Backend/Dockerfile
    container_name: duet-backend
    restart: always
    env_file:
      - ../.env
    networks:
      - traefik_net

  frontend:
    build:
      context: ..
      dockerfile: docker/Frontend/Dockerfile
    container_name: duet-frontend
    restart: always
    env_file:
      - ../.env
    networks:
      - traefik_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.duet-frontend.rule=Host(`duet.shreyansh-dev.app`)
      - traefik.http.routers.duet-frontend.entrypoints=websecure
      - traefik.http.routers.duet-frontend.tls=true
      - traefik.http.services.duet-frontend.loadbalancer.server.port=3000

networks:
  traefik_net:
    external: true
